version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: mysql_db_pp
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "2205:3306"
    volumes:
      - mysql_pp:/var/lib/mysql  
    networks:
      - ppmon  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_pp
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "2206:80"
    depends_on:
      - db
    networks:
      - ppmon  

networks:
  ppmon:  
    driver: bridge

volumes:
  mysql_pp:  
    driver: local
